sources:
  - name: staging
    database: my-project-de-502211 # Or name of your GCP project
    schema: zoomcamp # Or name of your BigQuery dataset

    tables:
      - name: green_tripdata
      - name: yellow_tripdata